import { Rekord } from '../models/rekord.model';
//import {Medication, Effective, Perfomer, Dosage, Rate  } from '../database/rekord.database';

export const REKORDS: Rekord[] = [
    {
        identifier: 1,
        instantiates: 'protokoll1',
        partOf: 'esemeny',
        status: 'kész',
        statusReason: 'mert készen van',
        category: 'kategória1',
        medication: {medicationCodeableConcept: "mcc",medicationReference: "mr"},
        subject: 'öregek',
        context: 'kétszer volt itt, kapjon algopyrint',
        supportInformation: '180cm, 50kg,',
        effective: {effectiveDateTime: '2000.12.03', effectivePeriod:'2012.02.03-2012.04.02'},
        performer: {function:'function', actor:'actor'},
        reasonCode: 'Fájt a hasa',
        reasonReference: 'Bejött és a hasa fájt',
        request: 'Hivatalos igénylés',
        device: 'Laptopról',
        note: 'Nincs megjegyzés',
        dosage: {text: 'text', site: 'site', route: 'route', method: 'method', dose: 'dose', rate: {rateRatio: 'rateRato', rateQuantity: 'rateQuantity'}},
        eventHistory: 'nincs1',
    },
    {
        identifier: 2,
        instantiates: 'protokoll2',
        partOf: 'esemeny2',
        status: 'kész2',
        statusReason: 'mert készen van2',
        category: 'kategória2',
        medication: {medicationCodeableConcept: 'mcc',medicationReference: 'mr'},
        subject: 'öregek2',
        context: 'kétszer volt itt, kapjon algopyrint2',
        supportInformation: '180cm, 50kg 2',
        effective: {effectiveDateTime: '2000.12.03', effectivePeriod:'2012.02.03-2012.04.02'},
        performer: {function:'function', actor:'actor'},
        reasonCode: 'Fájt a hasa 2',
        reasonReference: 'Bejött és a hasa fájt 2',
        request: 'Hivatalos igénylés 2',
        device: 'Laptopról 2',
        note: 'Nincs megjegyzés 2',
        dosage: {text: 'text', site: 'site', route: 'route', method: 'method', dose: 'dose', rate: {rateRatio: 'rateRato', rateQuantity: 'rateQuantity'}},
        eventHistory:'nincs2',
    },
    {
        identifier: 3,
        instantiates: 'protokoll3',
        partOf: 'esemeny3',
        status: 'kész3',
        statusReason: 'mert készen van3',
        category: 'kategória3',
        medication: {medicationCodeableConcept: 'mcc',medicationReference: 'mr'},
        subject: 'öregek3',
        context: 'kétszer volt itt, kapjon algopyrint3',
        supportInformation: '180cm, 50kg,3',
        effective: {effectiveDateTime: '2000.12.03', effectivePeriod:'2012.02.03-2012.04.02'},
        performer: {function:'function', actor:'actor'},
        reasonCode: 'Fájt a hasa3',
        reasonReference: 'Bejött és a hasa fájt3',
        request: 'Hivatalos igénylés3',
        device: 'Laptopról3',
        note: 'Nincs megjegyzés3',
        dosage: {text: 'text', site: 'site', route: 'route', method: 'method', dose: 'dose', rate: {rateRatio: 'rateRato', rateQuantity: 'rateQuantity'}},
        eventHistory:'nincs3',
    },
    {
        identifier: 4,
        instantiates: 'protokoll4',
        partOf: 'esemeny4',
        status: 'kész4',
        statusReason: 'mert készen van4',
        category: 'kategória4',
        medication: {medicationCodeableConcept: 'mcc',medicationReference: 'mr'},
        subject: 'öregek4',
        context: 'kétszer volt itt, kapjon algopyrint4',
        supportInformation: '180cm, 50kg,4',
        effective: {effectiveDateTime: '2000.12.03', effectivePeriod:'2012.02.03-2012.04.02'},
        performer: {function:'function', actor:'actor'},
        reasonCode: 'Fájt a hasa4',
        reasonReference: 'Bejött és a hasa fájt4',
        request: 'Hivatalos igénylés4',
        device: 'Laptopról4',
        note: 'Nincs megjegyzés4',
        dosage: {text: 'text', site: 'site', route: 'route', method: 'method', dose: 'dose', rate: {rateRatio: 'rateRato', rateQuantity: 'rateQuantity'}},
        eventHistory:'nincs4',
    },
    {
        identifier: 4,
        instantiates: 'protokoll4',
        partOf: 'esemeny4',
        status: 'kész4',
        statusReason: 'mert készen van4',
        category: 'kategória4',
        medication: {medicationCodeableConcept: 'mcc',medicationReference: 'mr'},
        subject: 'öregek4',
        context: 'kétszer volt itt, kapjon algopyrint4',
        supportInformation: '180cm, 50kg,4',
        effective: {effectiveDateTime: '2000.12.03', effectivePeriod:'2012.02.03-2012.04.02'},
        performer: {function:'function', actor:'actor'},
        reasonCode: 'Fájt a hasa4',
        reasonReference: 'Bejött és a hasa fájt4',
        request: 'Hivatalos igénylés4',
        device: 'Laptopról4',
        note: 'Nincs megjegyzés4',
        dosage: {text: 'text', site: 'site', route: 'route', method: 'method', dose: 'dose', rate: {rateRatio: 'rateRato', rateQuantity: 'rateQuantity'}},
        eventHistory:'nincs4',
    },
    {
        identifier: 4,
        instantiates: 'protokoll4',
        partOf: 'esemeny4',
        status: 'kész4',
        statusReason: 'mert készen van4',
        category: 'kategória4',
        medication: {medicationCodeableConcept: 'mcc',medicationReference: 'mr'},
        subject: 'öregek4',
        context: 'kétszer volt itt, kapjon algopyrint4',
        supportInformation: '180cm, 50kg,4',
        effective: {effectiveDateTime: '2000.12.03', effectivePeriod:'2012.02.03-2012.04.02'},
        performer: {function:'function', actor:'actor'},
        reasonCode: 'Fájt a hasa4',
        reasonReference: 'Bejött és a hasa fájt4',
        request: 'Hivatalos igénylés4',
        device: 'Laptopról4',
        note: 'Nincs megjegyzés4',
        dosage: {text: 'text', site: 'site', route: 'route', method: 'method', dose: 'dose', rate: {rateRatio: 'rateRato', rateQuantity: 'rateQuantity'}},
        eventHistory:'nincs4',
    },
];