import { Rekord } from '../models/rekord.model';

export const REKORDS: Rekord[] = [
    {
        identifier: 1,
        instantiates: 'protokoll1',
        partOf: 'esemeny',
        status: 'kész',
        statusReason: 'mert készen van',
        category: 'kategória1',
        medication: 'AlgoPyrin',
        subject: 'öregek',
        context: 'kétszer volt itt, kapjon algopyrint',
        supportInformation: '180cm, 50kg,',
        effective: '2020.12.03. - 2021.03.01.',
        performer: 'Dr.Bendi',
        reasonCode: 'Fájt a hasa',
        reasonReference: 'Bejött és a hasa fájt',
        request: 'Hivatalos igénylés',
        device: 'Laptopról',
        note: 'Nincs megjegyzés',
        dosage: '6x2 midnennap',
        eventHistory: 'nincs1',
    },
    {
        identifier: 2,
        instantiates: 'protokoll2',
        partOf: 'esemeny2',
        status: 'kész2',
        statusReason: 'mert készen van2',
        category: 'kategória2',
        medication: 'AlgoPyrin2',
        subject: 'öregek2',
        context: 'kétszer volt itt, kapjon algopyrint2',
        supportInformation: '180cm, 50kg 2',
        effective: '2020.12.03. - 2021.03.01. 2 ',
        performer: 'Dr.Bendi 2',
        reasonCode: 'Fájt a hasa 2',
        reasonReference: 'Bejött és a hasa fájt 2',
        request: 'Hivatalos igénylés 2',
        device: 'Laptopról 2',
        note: 'Nincs megjegyzés 2',
        dosage: '6x2 midnennap 2',
        eventHistory:'nincs2',
    },
    {
        identifier: 3,
        instantiates: 'protokoll3',
        partOf: 'esemeny3',
        status: 'kész3',
        statusReason: 'mert készen van3',
        category: 'kategória3',
        medication: 'AlgoPyrin3',
        subject: 'öregek3',
        context: 'kétszer volt itt, kapjon algopyrint3',
        supportInformation: '180cm, 50kg,3',
        effective: '2020.12.03. - 2021.03.01.3',
        performer: 'Dr.Bendi3',
        reasonCode: 'Fájt a hasa3',
        reasonReference: 'Bejött és a hasa fájt3',
        request: 'Hivatalos igénylés3',
        device: 'Laptopról3',
        note: 'Nincs megjegyzés3',
        dosage: '6x2 midnennap3',
        eventHistory:'nincs3',
    },
    {
        identifier: 4,
        instantiates: 'protokoll4',
        partOf: 'esemeny4',
        status: 'kész4',
        statusReason: 'mert készen van4',
        category: 'kategória4',
        medication: 'AlgoPyrin4',
        subject: 'öregek4',
        context: 'kétszer volt itt, kapjon algopyrint4',
        supportInformation: '180cm, 50kg,4',
        effective: '2020.12.03. - 2021.03.01.4',
        performer: 'Dr.Bendi4',
        reasonCode: 'Fájt a hasa4',
        reasonReference: 'Bejött és a hasa fájt4',
        request: 'Hivatalos igénylés4',
        device: 'Laptopról4',
        note: 'Nincs megjegyzés4',
        dosage: '6x2 midnennap4',
        eventHistory:'nincs4',
    },
];